on:
  pull_request:
        branches:
            - master
            - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry config virtualenvs.create false

      - name: Recreate coverage file
        run: |
          poetry install
          coverage run --branch -m pytest
          coverage xml -o coverage/coverage.xml

      - name: Get Cover
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: coverage/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
